name: Criar issue
on:
  - push
  - workflow_dispatch
jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Criar issue usando a API REST do GitHub
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Issue automatica para o commit: ${{ github.sha }}",
            "body": "Fazendo a minha primeira issue **${{ github.workflow }}**. \n\n O hash do commit foi: _${{ github.sha }}_."
            }' \
          --fail
      - name: Mandar mensagem no discrod
        run: |
          curl --request POST \
          --url https://discord.com/api/webhooks/816644781270630471/vTZV1euVk14-3nirOwTtavRloPGvXWtee-k6KN8dzwK4kUSRPmjFCXpH_kWgKi_P4GKo \
          --header 'content-type: application/json' \
          --header 'user-agent: vscode-restclient' \
          --data '{"username": "Doge","avatar_url": "https://i.pinimg.com/originals/2b/be/15/2bbe1591e28725b3f04217fee988b5e1.jpg","content": "WOW"}' 