name: Criar issue
on:
- push
jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Criar issue usando a API REST do GitHub
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "title": "Issue automatica para o commit: ${{ github.sha }}",
          "body": "Fazendo a minha primeira issue **${{ github.workflow }}**. \n\n O hash do commit foi: _${{ github.sha }}_."
          }' \
        --fail
